# on: push
# name: ðŸš€ Deploy website on push
# jobs:
#   web-deploy:
#     name: ðŸŽ‰ Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: ðŸšš Get latest code
#       uses: actions/checkout@v3

#     - name: Use Node.js 16
#       uses: actions/setup-node@v2
#       with:
#         node-version: '16'
      
#     - name: ðŸ”¨ Build Project
#       run: |
#         whoami
#         exec bash
#         git pull origin main
#         git status
#         npm install
#         pm2 restart 0
    
#     - name: ðŸ“‚ Sync files
#       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#       with:
#         server: ${{ secrets.FTP_SERVER }}
#         username: ${{ secrets.FTP_USERNAME }}
#         password: ${{ secrets.FTP_PASSWORD }}
